### ISSUE TITLE
خطا در core 1.1

### ISSUE THREAD

**Issue by hofa77** [pMonfared/CustomizeAspdotnetCore#2]
سلام

در 1.1 در لایه 
ioc

در خط مربوط به 
  config.For<IUserStore<ApplicationUser>>().ContainerScoped()
                .Use<UserStore<ApplicationUser,ApplicationRole,ApplicationDbContext,int,ApplicationUserClaim,ApplicationUserRole,ApplicationUserLogin,ApplicationUserToken>>();

روی ApplicationRole
خطا میده

متن خطا 
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0311	The type 'SampleFive.DomainLayer.Models.ApplicationRole' cannot be used as type parameter 'TRole' in the generic type or method 'UserStore<TUser, TRole, TContext, TKey, TUserClaim, TUserRole, TUserLogin, TUserToken>'. There is no implicit reference conversion from 'SampleFive.DomainLayer.Models.ApplicationRole' to 'Microsoft.AspNetCore.Identity.EntityFrameworkCore.IdentityRole<int, SampleFive.DomainLayer.Models.ApplicationUserRole, Microsoft.AspNetCore.Identity.EntityFrameworkCore.IdentityRoleClaim<int>>'.	SampleFive.IoC..NETCoreApp,Version=v1.1	E:\netCorePractice\Asp.netCoreMultiLayer-master\src\SampleFive.IoC\AppIocConfig.cs	32	Active

میشه لطفا راهنمایی کنید

با تشکر از زحماتتون

**Comment by hofa77** [comment]
مشکل رو پیدا کردم
در امضا کم داشت
,ApplicationRoleClaim

          config.For<IUserStore<ApplicationUser>>().ContainerScoped()
                .Use<UserStore<ApplicationUser, ApplicationRole, ApplicationDbContext, int, ApplicationUserclaim, ApplicationUserRole, ApplicationUserLogin, ApplicationUsertoken,ApplicationRoleClaim>>();

**Comment by pMonfared** [comment]
بسیار عالی، ببخشید جواب ندادم خیلی سرم شلوغ بود.

**Comment by hofa77** [comment]
خواهش میکنم
تلاش قابل تقدیرتون در این پروژه ستودنی هست 
تشکر از اینکه به اشتراک گذاشتید

**Comment by pMonfared** [comment]
امکانش اگر وجود داره در مورد حل این مشکل کمی توضیح بدین ممنونم میشم. و کدی که مشکل رو حل کرده به اشتراک بذارین

**Comment by hofa77** [comment]
dar layer Ioc rooye line 31 error dasht 
ke hamoontor ke neveshtam dar akhare in khat in ro kam dasht   ApplicationRoleClaim

va kolle in khat taghir mikone be in line 

    config.For<IUserStore<ApplicationUser>>().ContainerScoped()
            .Use<UserStore<ApplicationUser, ApplicationRole, ApplicationDbContext, int, ApplicationUserclaim, ApplicationUserRole, ApplicationUserLogin, ApplicationUsertoken,ApplicationRoleClaim>>();

faghat **ApplicationRoleClaim**  ezafe shod be akhare in khat
