### ISSUE TITLE
حذف شدن لایه IOC

### ISSUE THREAD

**Issue by hofa77** [pMonfared/CustomizeAspdotnetCore#3]
سلام
چرا لایه 
IOC
حذف شده است از پروژه
باعث بروز خطا شده است

**Comment by pMonfared** [comment]
در مسیر پروژه وجود داره، حذف نشده
منظورتون رو متوجه نمیشم کمی بیشتر توضیح بدین

**Comment by hofa77** [comment]
بله الان دیدمش
عذرخواهی میکنم
