### ISSUE TITLE
خطا در IOC

### ISSUE THREAD

**Issue by hofa77** [pMonfared/CustomizeAspdotnetCore#4]
سلام 
در زمان ران کردن پروژه خطای زیر در لایه آی او سی بوجود میاد
شما خطایی ندارید ؟

![error](https://cloud.githubusercontent.com/assets/23141367/22207385/320f3e40-e194-11e6-956e-ebba3beb7640.jpg)

جزییات خطا
`
Only concrete types can be built by ConstructorInstance.
Parameter name: concreteType
Actual value was Microsoft.AspNetCore.Identity.EntityFrameworkCore.UserStore`9[SampleFive.DomainLayer.Models.ApplicationUser,SampleFive.DomainLayer.Models.ApplicationRole,SampleFive.DataLayer.Context.ApplicationDbContext,System.Int32,SampleFive.DomainLayer.Models.ApplicationUserClaim,SampleFive.DomainLayer.Models.ApplicationUserRole,SampleFive.DomainLayer.Models.ApplicationUserLogin,SampleFive.DomainLayer.Models.ApplicationUserToken,SampleFive.DomainLayer.Models.ApplicationRoleClaim].
`

اگر جناب نصیری هم بتونن خطا رو ببینن خیلی خوب میشه
@VahidN

با تشکر

**Comment by VahidN** [comment]
<div dir="rtl">
من در مورد مقدمات سفارشي سازي ASP.NET Core Identity در اينجا چند نكته رو عنوان كردم كه بايد اعمال كنيد
(نكات مطلب را بايد از ابتدا تا انتها اعمال كنيد)

https://github.com/aspnet/Identity/issues/1082#issuecomment-273514725
در كل در حال كار بر روي يك پروژه‌ي جامع مرتبط هستم كه تا يك ماه ديگر منتشر مي‌شود
